### ISSUE TITLE
scheduler caught exception: execution expired

### ISSUE THREAD

**Issue by tooh** [nahi/httpclient#225]
Hi I use the dashing application. This application uses rufus-scheduler.
In my dashing job I use httpclient to get content.

I recently started using httpclient so I don't know the exact use of this module.

The job is running every 60s.
It works OK for a while and then the below errors are reported:

```
/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/openssl/buffering.rb:53:in `sysread'
/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/openssl/buffering.rb:53:in `fill_rbuff'
/.rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/openssl/buffering.rb:200:in `gets'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient/session.rb:352:in `gets'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient/session.rb:881:in `block in parse_header'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient/session.rb:877:in `parse_header'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient/session.rb:860:in `read_header'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient/session.rb:667:in `get_header'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:1202:in `do_get_header'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:1151:in `do_get_block'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:952:in `block in do_request'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:1046:in `protect_keep_alive_disconnected'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:951:in `do_request'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:813:in `request'
/.rvm/gems/ruby-1.9.3-p547/gems/httpclient-2.5.2/lib/httpclient.rb:713:in `post'
```

**Comment by hickscorp** [comment]
We recently started having this problem sporadically. First in our dev machines, then in production.
We do not use HTTPClient directly, we use gems that themselve use HTTPClient.
The stack trace is extremelly vague, but if you start looking for it you'll find people having the problem and never really finding a solution to it, it just randomly disappears.

It can occur when using gems such as the Instagram official client, or [koala](https://github.com/arsduo/koala).

The bug is completelly random. I'm wondering if some lower level issue might be in play here.

Any insights?
Thanks!

In our case, an example stacktrace:
```
Timeout::Error: execution expired
  from /usr/local/lib/ruby/2.3.0/openssl/buffering.rb:57:in `sysread'
  from /usr/local/lib/ruby/2.3.0/openssl/buffering.rb:57:in `fill_rbuff'
  from /usr/local/lib/ruby/2.3.0/openssl/buffering.rb:204:in `gets'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/ssl_socket.rb:62:in `gets'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:805:in `block in parse_header'
  from /usr/local/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
  from /usr/local/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient/session.rb:561:in `get_header'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1299:in `do_get_header'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1245:in `do_get_block'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
... 31 levels...
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/cache.rb:299:in `fetch'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:207:in `request'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:196:in `block (2 levels) in <class:Facebook>'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:260:in `setup_account'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:52:in `block in setup'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:50:in `each'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:50:in `all?'
  from /var/deploy/REDACTED/web_head/releases/20170329190708/app/models/advert_adapters/facebook.rb:50:in `setup'
  from (irb):2
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  from /var/deploy/REDACTED/web_head/shared/bundle/ruby/2.3.0/gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
  from bin/rails:8:in `require'
  from bin/rails:8:in `<main>'
```

**Comment by hickscorp** [comment]
Could anyone please give me a commit which supposedly fixed this? We're getting this exception all over the place one day, and not at all the next day.
