### ISSUE TITLE
Upgrading to 2.5.3 results in SSL errors

### ISSUE THREAD

**Issue by lucaspiller** [nahi/httpclient#230]
I've just upgraded to 2.5.3.2 and now get an error whenever trying to make a SSL connection with a client certificate:

```
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.7/lib/httpi/adapter/httpclient.rb:28:in `rescue in request'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.7/lib/httpi/adapter/httpclient.rb:25:in `request'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.7/lib/httpi.rb:159:in `request'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/httpi-2.2.7/lib/httpi.rb:131:in `post'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/operation.rb:86:in `block in call_with_logging'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/request_logger.rb:12:in `call'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/request_logger.rb:12:in `log'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/operation.rb:86:in `call_with_logging'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/operation.rb:51:in `call'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/savon-2.7.2/lib/savon/client.rb:36:in `call'
*snip*
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:60:in `load'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/runner.rb:60:in `<top (required)>'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:128:in `require'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:128:in `require_command!'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:95:in `runner'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
/Users/luca/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.1.7/lib/rails/commands.rb:17:in `<top (required)>'
bin/rails:8:in `require'
bin/rails:8:in `<main>'
SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed
```

I've tested the certificates directly with OpenSSL and it works fine, as does downgrading to 2.5.2.

**Comment by nahi** [comment]
https://github.com/nahi/httpclient/commit/e70ec73cbb45ade4551d0578a0a0643662069426 solved this issue.
