### ISSUE TITLE
HTTPClient::ReceiveTimeoutError: (execution expired)

### ISSUE THREAD

**Issue by navyah** [nahi/httpclient#249]
I am unable to login to the application if the app is launched from instruments.

**Comment by hickscorp** [comment]
Not sure if that's what this is issue is about, is it something like [this](https://github.com/nahi/httpclient/issues/225)?

**Comment by vnazarenko** [comment]
Actually the same for me. Randomly, when i use proxy, i got this
2.3.0 :042 >   r = clnt.get("https://google.com", follow_redirect: true)
= Request

! CONNECT TO 217.xx.xx.xx:6523
HTTPClient::ConnectTimeoutError: execution expired
	from /var/www2/instaplus/shared/bundle/ruby/2.3.0/bundler/gems/httpclient-6c3a1258234f/lib/httpclient/session.rb:597:in `initialize'
	from /var/www2/instaplus/shared/bundle/ruby/2.3.0/bundler/gems/httpclient-6c3a1258234f/lib/httpclient/session.rb:597:in `new'
	from /var/www2/instaplus/shared/bundle/ruby/2.3.0/bundler/gems/httpclient-6c3a1258234f/lib/httpclient/session.rb:597:in `create_socket'
	from /var/www2/instaplus/shared/bundle/ruby/2.3.0/bundler/gems/httpclient-6c3a1258234f/lib/httpclient/ssl_socket.rb:18:in `create_socket'
	from /var/www2/instaplus/shared/bundle/ruby/2.3.0/bundler/gems/httpclient-6c3a1258234f/lib/httpclient/session.rb:739:in `block in connect'
	from /usr/local/rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/timeout.rb:101:in `timeout'

We have several production servers, and on some of them it works, but on some i'm getting expired error
