### ISSUE TITLE
Getting head ignores timeouts

### ISSUE THREAD

**Issue by binaryplease** [nahi/httpclient#256]
Hi, 

I set timeouts with

````ruby
    httpclient.connect_timeout = 10
    httpclient.send_timeout = 10
    httpclient.receive_timeout = 10
    httpclient.keep_alive_timeout = 10

````

They work fine for get_content but getting the head with
````ruby
head = httpclient.head(url, follow_redirect: true)
````
ignores them. There should be an option to deal with slow servers.

Pablo.

**Comment by binaryplease** [comment]
Heres a backtrace for a Thread that got Stuck getting the header:
````
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `gets'                     |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:876:in `parse_header'             |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `timeout'                  |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:872:in `parse_header'             |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:855:in `read_header'              |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient/session.rb:662:in `get_header'               |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:1247:in `do_get_header'                   |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:1194:in `do_get_block'                    |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:974:in `do_request'                       |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:1082:in `protect_keep_alive_disconnected' |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:969:in `do_request'                       |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:1053:in `follow_redirect'                 |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:820:in `request'                          |
| 19                            | /home/binaryplease/.rvm/gems/jruby-1.7.19/gems/httpclient-2.6.0.1/lib/httpclient.rb:708:in `head'  


````

**Comment by nahi** [comment]
As the discussion in https://github.com/nahi/httpclient/pull/258 it should be JRuby's issue. Please try to update JRuby.
