### ISSUE TITLE
Excessive Cookie#domain warning logging 

### ISSUE THREAD

**Issue by kat3kasper** [nahi/httpclient#263]
We are seeing excessive logging of `Cookie#domain returns dot-less domain name now. Use Cookie#dot_domain if you need "." at the beginning.`

I raised an exception there and from the stack trace it appears to be caused from httpclient using http-cookie.  Is there a way to remove or suppress these warnings? We are getting hundreds a minute

```
2015-09-11T18:17:02.069Z 31967 TID-owe3lhuek WARN: /srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:197:in `domain'
/srv/cm/shared/bundle/ruby/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie.rb:460:in `origin='
/srv/cm/shared/bundle/ruby/2.2.0/gems/http-cookie-1.0.2/lib/http/cookie.rb:204:in `initialize'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:34:in `new'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:34:in `block in cookies'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:33:in `map'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:33:in `cookies'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient/cookie.rb:49:in `cookie_value'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:1131:in `create_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:963:in `do_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/httpclient-2.6.0.1/lib/httpclient.rb:822:in `request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/adapter/httpclient.rb:33:in `call'
/srv/cm/shared/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
/srv/cm/shared/bundle/ruby/2.2.0/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `call'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/base.rb:187:in `perform_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-transport-1.0.6/lib/elasticsearch/transport/client.rb:111:in `perform_request'
/srv/cm/shared/bundle/ruby/2.2.0/gems/elasticsearch-api-1.0.6/lib/elasticsearch/api/actions/bulk.rb:80:in `bulk'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:70:in `bulk'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:32:in `block (2 levels) in import'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:121:in `block in import_objects'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:115:in `each_slice'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:115:in `each'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:115:in `map'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:115:in `import_objects'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/adapter/orm.rb:86:in `import'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:28:in `block in import'
/srv/cm/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `block in instrument'
/srv/cm/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/srv/cm/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.1/lib/active_support/notifications.rb:164:in `instrument'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:27:in `import'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/type/import.rb:59:in `import!'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/strategy/sidekiq.rb:17:in `perform'
/srv/cm/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:75:in `execute_job'
/srv/cm/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/processor.rb:52:in `block (2 levels) in process'
/srv/cm/shared/bundle/ruby/2.2.0/gems/sidekiq-3.4.2/lib/sidekiq/middleware/chain.rb:127:in `block in invoke'
/srv/cm/releases/20150911174122/app/middleware/sidekiq_chewy_request_strategy.rb:6:in `block in call'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy/strategy.rb:54:in `wrap'
/srv/cm/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/chewy.rb:160:in `strategy'
```

**Comment by kat3kasper** [comment]
Submitted PR https://github.com/nahi/httpclient/pull/265
