### ISSUE TITLE
Zlib::GzipFile::Error

### ISSUE THREAD

**Issue by pbstriker38** [nahi/httpclient#359]
Ruby: 2.3.1
HTTPClient: 2.8.3

Getting a `Zlib::GzipFile::Error` when I enable `transparent_gzip_decompression`

Steps to reproduce:
```
client = HTTPClient.new
client.transparent_gzip_decompression = true
client.get("http://www.news-medical.net")
```
```
Zlib::GzipFile::Error: not in gzip format
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httplog-0.3.3/lib/httplog/http_log.rb:101:in `initialize'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httplog-0.3.3/lib/httplog/http_log.rb:101:in `new'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httplog-0.3.3/lib/httplog/http_log.rb:101:in `log_body'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httplog-0.3.3/lib/httplog/adapters/httpclient.rb:30:in `do_get_block'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.3/lib/httpclient.rb:1019:in `block in do_request'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.3/lib/httpclient.rb:1133:in `protect_keep_alive_disconnected'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.3/lib/httpclient.rb:1014:in `do_request'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.3/lib/httpclient.rb:856:in `request'
	from /Users/d/.rvm/gems/ruby-2.3.1/gems/httpclient-2.8.3/lib/httpclient.rb:743:in `get'
```

**Comment by pbstriker38** [comment]
Looks like an issue with the gem httplog
