### ISSUE TITLE
HTTPClient::KeepAliveDisconnected

### ISSUE THREAD

**Issue by tommybernaciak** [nahi/httpclient#391]
Hi, I am getting this error, I think this is gem issue. 

`HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected: Connection reset by peer`

stacktrace:
```
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:900:in `rescue in block in parse_header'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:891:in `block in parse_header'
/opt/rubies/2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
/opt/rubies/2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `call'
/opt/rubies/2.1.5/lib/ruby/2.1.0/timeout.rb:101:in `timeout'
/opt/rubies/2.1.5/lib/ruby/2.1.0/timeout.rb:127:in `timeout'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:888:in `parse_header'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:871:in `read_header'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient/session.rb:678:in `get_header'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1215:in `do_get_header'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1164:in `do_get_block'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:962:in `block in do_request'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1064:in `rescue in protect_keep_alive_disconnected'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:1058:in `protect_keep_alive_disconnected'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:961:in `do_request'
/vendor/bundle/ruby/2.1.0/gems/httpclient-2.5.3.3/lib/httpclient.rb:823:in `request'
```

Please could you take a look or tell me how to fix this?

**Comment by shivanshgaur** [comment]
Try updating httpclient to version `2.8.3` and see if you still get these errors.

**Comment by ibtehaj-dnt** [comment]
Did anyone fix this issue?
I'm facing the same issue on `version 2.8.3`
`Rack app error handling request { PATCH .......}
#<HTTPClient::KeepAliveDisconnected: HTTPClient::KeepAliveDisconnected: >
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:808:in `block in parse_header'
/usr/local/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/usr/local/lib/ruby/2.7.0/timeout.rb:105:in `timeout'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:801:in `parse_header'
/usr/local/bundle/gems/httpclient-2.8.3/lib/httpclient/session.rb:784:in `read_header'
`

**Comment by jpriollaud** [comment]
@ibtehaj-dnt are you using httpclient in a background job of some kind?
